service: pmv

provider:
  name: aws
  runtime: python2.7
  region: ap-southeast-1
  stage: dev
  memorySize: 1536
  timeout: 300

functions:
  computePMV:
    handler: handler.handler
    events:
      - http:
          path: pmv
          method: get
          cors: true
